### ISSUE TITLE
Support for JJB v2.0

### ISSUE THREAD

**Issue by jtyr** [bgaifullin/jenkins-job-builder-active-choice#2]
I'm trying to use this extension with JJB v2.0.6 and I'm getting the following error:

```
$ jenkins-jobs --conf builder.cfg  --user $BUILD_USER_ID --password $BUILD_USER_TOKEN update jobs.yaml
INFO:jenkins_jobs.cli.subcommand.update:Updating jobs in ['jenkins/builder/golden_image_pipeline.yaml'] ([])
Traceback (most recent call last):
  File "/usr/local/bin/jenkins-jobs", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/cli/entry.py", line 146, in main
    jjb.execute()
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/cli/entry.py", line 140, in execute
    ext.obj.execute(self.options, self.jjb_config)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/cli/subcommand/update.py", line 135, in execute
    options, jjb_config)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/cli/subcommand/update.py", line 114, in _generate_xmljobs
    xml_jobs = xml_job_generator.generateXML(job_data_list)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/xml_config.py", line 77, in generateXML
    xml_jobs.append(self._getXMLForJob(job))
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/xml_config.py", line 88, in _getXMLForJob
    self._gen_xml(xml, data)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/xml_config.py", line 98, in _gen_xml
    module.gen_xml(xml, data)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/modules/parameters.py", line 1022, in gen_xml
    self.registry.dispatch('parameter', pdefs, param)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/registry.py", line 260, in dispatch
    format(name, component_type))
jenkins_jobs.errors.JenkinsJobsException: Unknown entry point or macro 'active-choice' for component type: 'parameter'.

$ pip list | grep jenkins-job-builder
jenkins-job-builder (2.0.6)
jenkins-job-builder-active-choice (0.0.4)
```

Am I missing something or is JJB v2.0+ not yet supported?

**Comment by blackprowler** [comment]
the same issue for the `jenkins-job-builder (2.1.0)`
does it still under support?

**Comment by armyers** [comment]
I think you need to use 'cascade-choice' rather than 'active-choice' as the parameter type. HTH.

**Comment by bgaifullin** [comment]
I do not support this library more.
